apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-chat-deployment
  labels:
    app: chat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: gcr.io/gcp-docker-kubernetes-414203/chat:1.0.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: spring-chat-config
        resources:
          requests:
            cpu: "200m"
--- #for a single file
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-chat-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-chat-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75